version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres_db'
    environment:
      - POSTGRES_DB=challengeDB
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5432:5432'
    volumes:
      - './init-scripts:/docker-entrypoint-initdb.d'
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d challengeDB"]
      interval: 10s
      retries: 10
      timeout: 20s
      start_period: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/challengeDB?currentSchema=matches
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  pgdata:
